/**
 * WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from '././sex';
import { GroupDTO } from '././groupDTO';
import { FormControl, FormGroup, FormArray, Validators } from '@angular/forms';
/*
https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables
*/
import { BaseModel } from '../variables';

/**
 * Generated Model Interface for Model "PersonDTO"
 *
 */
export interface IPersonDTO {

    id?: number;
    birth?: string;
    firstName?: string;
    groups?: Array<GroupDTO>;
    lastName?: string;
    sex?: Sex;
}
/**
 * Generated Model Class for Model "PersonDTO"
 *
 */
export class PersonDTO extends BaseModel implements IPersonDTO {
    public  static readonly MODEL  = 'PersonDTO';
    public                  MODEL  = 'PersonDTO';


    public id?: number;
    public birth?: string;
    public firstName?: string;
    public groups?: Array<GroupDTO>;
    public lastName?: string;
    public sex?: Sex;


    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
       super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }

        // define non enumerable properties so these are omitted in JSON.stringify.
        Object.defineProperty(this, 'MODEL', {
            enumerable: false,
            writable: false
        });
    }


    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
     */
    public setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);

            this.id = this.castTo('number', rawValues.id);

            this.birth = this.castTo('string', rawValues.birth);

            this.firstName = this.castTo('string', rawValues.firstName);
            this.groups = rawValues.groups ? rawValues.groups
                    .map(_ => {
                        return GroupDTO && GroupDTO['prototype']
                            ? ( _ ? Reflect.construct(<any>GroupDTO, [_]) : Reflect.construct(<any>GroupDTO, []) )
                            : _ ;
                    }) : null;

            this.lastName = this.castTo('string', rawValues.lastName);
        this.sex = rawValues.sex;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    /**
     * returns the FormGroup of that model
     */
    public getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup( {
            id: new FormControl(this.id, [] ),
            birth: new FormControl(this.birth, [] ),
            firstName: new FormControl(this.firstName, [] ),
            groups: new FormArray(this.groups ? this.groups
                .map(_ => {
                    return _ && _['getFormGroup'] ? _['getFormGroup']() : new FormControl(_, [])
                }) : []),
            // groups: new FormControl(this.groups, [] ),
            lastName: new FormControl(this.lastName, [] ),
            sex: new FormControl(this.sex, [] ),

            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    public setFormGroupValues() {
        this.$formGroup.controls['id'].setValue(this.id);
        this.$formGroup.controls['birth'].setValue(this.birth);
        this.$formGroup.controls['firstName'].setValue(this.firstName);
        this.$formGroup.controls['groups'].setValue(this.groups);
        this.$formGroup.controls['lastName'].setValue(this.lastName);
        this.$formGroup.controls['sex'].setValue(this.sex);

        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }

    /**
     * checks, if attribute is required for this model
     */
    public isRequired(attribute: string): boolean {
        switch (attribute) {
            case 'id': return false;
            case 'birth': return false;
            case 'firstName': return false;
            case 'groups': return false;
            case 'lastName': return false;
            case 'sex': return false;
            default: return false;
        }
    }
}



